Traceback (most recent call last):
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 31, in _load_model
    activity_model = self._load_container(parameters)
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 40, in _load_container
    scikit_model = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../Reinvent/input.py", line 40, in <module>
    manager.run()
  File "/home/springnuance/reinvent-hitl/Reinvent/running_modes/manager.py", line 17, in run
    runner = RunningMode(self.run_configuration)
  File "/home/springnuance/reinvent-hitl/Reinvent/running_modes/constructors/running_mode.py", line 18, in __new__
    return ReinforcementLearningModeConstructor(configuration)
  File "/home/springnuance/reinvent-hitl/Reinvent/running_modes/constructors/reinforcement_learning_mode_constructor.py", line 44, in __new__
    scoring_function = ScoringFunctionFactory(config.scoring_function)
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/scoring_function_factory.py", line 16, in __new__
    return cls.create_scoring_function_instance(sf_parameters, scoring_function_registry)
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/scoring_function_factory.py", line 25, in create_scoring_function_instance
    return scoring_function(parameters, sf_parameters.parallel)
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/function/custom_product.py", line 14, in __init__
    super().__init__(parameters, parallel)
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/function/base_scoring_function.py", line 62, in __init__
    self.scoring_components = factory.create_score_components()
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/score_components/score_component_factory.py", line 95, in create_score_components
    components = [create_component(component) for component in self._parameters]
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/score_components/score_component_factory.py", line 95, in <listcomp>
    components = [create_component(component) for component in self._parameters]
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/score_components/score_component_factory.py", line 89, in create_component
    component_instance = component(component_params)
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 16, in __init__
    self.activity_model = self._load_model(parameters)
  File "/home/springnuance/reinvent-hitl/Reinvent/reinvent_scoring/scoring/score_components/standard/predictive_property_component.py", line 34, in _load_model
    raise Exception(f"The loaded file `{model_path}` isn't a valid scikit-learn model")
Exception: The loaded file `/home/springnuance/reinvent-hitl/Reinvent-Community-Binh/notebooks/models/Aurora_model.pkl` isn't a valid scikit-learn model
